/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attachment {
  'hash' : string,
  'size' : bigint,
  'mimeType' : string,
  'filename' : string,
}
export interface Message {
  'id' : MessageId,
  'deletedBySender' : boolean,
  'deletedByRecipient' : boolean,
  'subject' : string,
  'body' : string,
  'recipient' : Principal,
  'trashedByRecipient' : boolean,
  'isRead' : boolean,
  'sender' : Principal,
  'timestamp' : Time,
  'threadId' : bigint,
  'parentId' : [] | [MessageId],
  'trashedBySender' : boolean,
  'attachments' : Array<Attachment>,
  'payment' : [] | [Payment],
}
export type MessageId = bigint;
export interface MessageInput {
  'subject' : string,
  'body' : string,
  'recipient' : Principal,
  'parentId' : [] | [MessageId],
  'attachments' : Array<Attachment>,
  'payment' : [] | [Payment],
}
export interface MessageUpdate {
  'subject' : [] | [string],
  'body' : [] | [string],
}
export interface Payment {
  'token' : string,
  'memo' : [] | [string],
  'amount' : bigint,
}
export interface ThreadMessageSummary {
  'participants' : Array<Principal>,
  'subject' : string,
  'messages' : Array<Message>,
  'totalMessages' : bigint,
  'unreadCount' : bigint,
  'latestMessage' : Message,
  'threadId' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'principal' : Principal,
  'username' : string,
  'registrationTime' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAllMessages' : ActorMethod<[], undefined>,
  'deleteMessage' : ActorMethod<[MessageId], undefined>,
  'deleteThread' : ActorMethod<[bigint], undefined>,
  'emptyTrash' : ActorMethod<[], undefined>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllMessagesByRecipient' : ActorMethod<[], Array<Message>>,
  'getAllMessagesBySender' : ActorMethod<[], Array<Message>>,
  'getAllMessagesBySenderAndRecipient' : ActorMethod<[], Array<Message>>,
  'getAllMessagesBySubject' : ActorMethod<[], Array<Message>>,
  'getAllMessagesByThread' : ActorMethod<[], Array<Message>>,
  'getAllMessagesByTimestamp' : ActorMethod<[], Array<Message>>,
  'getAllThreads' : ActorMethod<[], Array<ThreadMessageSummary>>,
  'getAllThreadsBySubject' : ActorMethod<[], Array<ThreadMessageSummary>>,
  'getAllThreadsByTimestamp' : ActorMethod<[], Array<ThreadMessageSummary>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, string]>>,
  'getAllUsersByPrincipal' : ActorMethod<[], Array<[Principal, string]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[Principal], Array<Message>>,
  'getInbox' : ActorMethod<[], Array<Message>>,
  'getInboxBySender' : ActorMethod<[], Array<Message>>,
  'getInboxBySubject' : ActorMethod<[], Array<Message>>,
  'getInboxByThread' : ActorMethod<[], Array<Message>>,
  'getMessageById' : ActorMethod<[MessageId], [] | [Message]>,
  'getOutbox' : ActorMethod<[], Array<Message>>,
  'getOutboxByRecipient' : ActorMethod<[], Array<Message>>,
  'getOutboxBySubject' : ActorMethod<[], Array<Message>>,
  'getOutboxByThread' : ActorMethod<[], Array<Message>>,
  'getOwnUsername' : ActorMethod<[], string>,
  'getPrincipalByUsername' : ActorMethod<[string], Principal>,
  'getThread' : ActorMethod<[bigint], Array<Message>>,
  'getTrash' : ActorMethod<[], Array<Message>>,
  'getUnreadMessageCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsernameByPrincipal' : ActorMethod<[Principal], string>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUsernameAvailable' : ActorMethod<[string], boolean>,
  'markAllMessagesAsRead' : ActorMethod<[], undefined>,
  'markMessageAsRead' : ActorMethod<[MessageId], undefined>,
  'register' : ActorMethod<[string], undefined>,
  'replyToMessage' : ActorMethod<[MessageId, string, string], MessageId>,
  'restoreThread' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedReplyChain' : ActorMethod<[[] | [bigint]], undefined>,
  'seedSampleMessages' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    undefined
  >,
  'sendMessage' : ActorMethod<[MessageInput], MessageId>,
  'sendMessageWithReply' : ActorMethod<[Message], undefined>,
  'trashThread' : ActorMethod<[bigint], undefined>,
  'updateMessage' : ActorMethod<[MessageId, MessageUpdate], undefined>,
  'updateUsername' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];