/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MessageId = IDL.Nat;
export const Time = IDL.Int;
export const Attachment = IDL.Record({
  'hash' : IDL.Text,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
});
export const Payment = IDL.Record({
  'token' : IDL.Text,
  'memo' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat64,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'deletedBySender' : IDL.Bool,
  'deletedByRecipient' : IDL.Bool,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'recipient' : IDL.Principal,
  'trashedByRecipient' : IDL.Bool,
  'isRead' : IDL.Bool,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'threadId' : IDL.Nat,
  'parentId' : IDL.Opt(MessageId),
  'trashedBySender' : IDL.Bool,
  'attachments' : IDL.Vec(Attachment),
  'payment' : IDL.Opt(Payment),
});
export const ThreadMessageSummary = IDL.Record({
  'participants' : IDL.Vec(IDL.Principal),
  'subject' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'totalMessages' : IDL.Nat,
  'unreadCount' : IDL.Nat,
  'latestMessage' : Message,
  'threadId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'registrationTime' : Time,
});
export const MessageInput = IDL.Record({
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'recipient' : IDL.Principal,
  'parentId' : IDL.Opt(MessageId),
  'attachments' : IDL.Vec(Attachment),
  'payment' : IDL.Opt(Payment),
});
export const MessageUpdate = IDL.Record({
  'subject' : IDL.Opt(IDL.Text),
  'body' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAllMessages' : IDL.Func([], [], []),
  'deleteMessage' : IDL.Func([MessageId], [], []),
  'deleteThread' : IDL.Func([IDL.Nat], [], []),
  'emptyTrash' : IDL.Func([], [], []),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllMessagesByRecipient' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllMessagesBySender' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllMessagesBySenderAndRecipient' : IDL.Func(
      [],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getAllMessagesBySubject' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllMessagesByThread' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllMessagesByTimestamp' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllThreads' : IDL.Func([], [IDL.Vec(ThreadMessageSummary)], ['query']),
  'getAllThreadsBySubject' : IDL.Func(
      [],
      [IDL.Vec(ThreadMessageSummary)],
      ['query'],
    ),
  'getAllThreadsByTimestamp' : IDL.Func(
      [],
      [IDL.Vec(ThreadMessageSummary)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
      ['query'],
    ),
  'getAllUsersByPrincipal' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getInbox' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getInboxBySender' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getInboxBySubject' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getInboxByThread' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getMessageById' : IDL.Func([MessageId], [IDL.Opt(Message)], ['query']),
  'getOutbox' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getOutboxByRecipient' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getOutboxBySubject' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getOutboxByThread' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getOwnUsername' : IDL.Func([], [IDL.Text], ['query']),
  'getPrincipalByUsername' : IDL.Func([IDL.Text], [IDL.Principal], ['query']),
  'getThread' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getTrash' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsernameByPrincipal' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'markAllMessagesAsRead' : IDL.Func([], [], []),
  'markMessageAsRead' : IDL.Func([MessageId], [], []),
  'register' : IDL.Func([IDL.Text], [], []),
  'replyToMessage' : IDL.Func([MessageId, IDL.Text, IDL.Text], [MessageId], []),
  'restoreThread' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedReplyChain' : IDL.Func([IDL.Opt(IDL.Nat)], [], []),
  'seedSampleMessages' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'sendMessage' : IDL.Func([MessageInput], [MessageId], []),
  'sendMessageWithReply' : IDL.Func([Message], [], []),
  'trashThread' : IDL.Func([IDL.Nat], [], []),
  'updateMessage' : IDL.Func([MessageId, MessageUpdate], [], []),
  'updateUsername' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MessageId = IDL.Nat;
  const Time = IDL.Int;
  const Attachment = IDL.Record({
    'hash' : IDL.Text,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
  });
  const Payment = IDL.Record({
    'token' : IDL.Text,
    'memo' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat64,
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'deletedBySender' : IDL.Bool,
    'deletedByRecipient' : IDL.Bool,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'recipient' : IDL.Principal,
    'trashedByRecipient' : IDL.Bool,
    'isRead' : IDL.Bool,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'threadId' : IDL.Nat,
    'parentId' : IDL.Opt(MessageId),
    'trashedBySender' : IDL.Bool,
    'attachments' : IDL.Vec(Attachment),
    'payment' : IDL.Opt(Payment),
  });
  const ThreadMessageSummary = IDL.Record({
    'participants' : IDL.Vec(IDL.Principal),
    'subject' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'totalMessages' : IDL.Nat,
    'unreadCount' : IDL.Nat,
    'latestMessage' : Message,
    'threadId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'registrationTime' : Time,
  });
  const MessageInput = IDL.Record({
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'recipient' : IDL.Principal,
    'parentId' : IDL.Opt(MessageId),
    'attachments' : IDL.Vec(Attachment),
    'payment' : IDL.Opt(Payment),
  });
  const MessageUpdate = IDL.Record({
    'subject' : IDL.Opt(IDL.Text),
    'body' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAllMessages' : IDL.Func([], [], []),
    'deleteMessage' : IDL.Func([MessageId], [], []),
    'deleteThread' : IDL.Func([IDL.Nat], [], []),
    'emptyTrash' : IDL.Func([], [], []),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllMessagesByRecipient' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllMessagesBySender' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllMessagesBySenderAndRecipient' : IDL.Func(
        [],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getAllMessagesBySubject' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllMessagesByThread' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllMessagesByTimestamp' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllThreads' : IDL.Func([], [IDL.Vec(ThreadMessageSummary)], ['query']),
    'getAllThreadsBySubject' : IDL.Func(
        [],
        [IDL.Vec(ThreadMessageSummary)],
        ['query'],
      ),
    'getAllThreadsByTimestamp' : IDL.Func(
        [],
        [IDL.Vec(ThreadMessageSummary)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
        ['query'],
      ),
    'getAllUsersByPrincipal' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getInbox' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getInboxBySender' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getInboxBySubject' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getInboxByThread' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getMessageById' : IDL.Func([MessageId], [IDL.Opt(Message)], ['query']),
    'getOutbox' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getOutboxByRecipient' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getOutboxBySubject' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getOutboxByThread' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getOwnUsername' : IDL.Func([], [IDL.Text], ['query']),
    'getPrincipalByUsername' : IDL.Func([IDL.Text], [IDL.Principal], ['query']),
    'getThread' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getTrash' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsernameByPrincipal' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'markAllMessagesAsRead' : IDL.Func([], [], []),
    'markMessageAsRead' : IDL.Func([MessageId], [], []),
    'register' : IDL.Func([IDL.Text], [], []),
    'replyToMessage' : IDL.Func(
        [MessageId, IDL.Text, IDL.Text],
        [MessageId],
        [],
      ),
    'restoreThread' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedReplyChain' : IDL.Func([IDL.Opt(IDL.Nat)], [], []),
    'seedSampleMessages' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'sendMessage' : IDL.Func([MessageInput], [MessageId], []),
    'sendMessageWithReply' : IDL.Func([Message], [], []),
    'trashThread' : IDL.Func([IDL.Nat], [], []),
    'updateMessage' : IDL.Func([MessageId, MessageUpdate], [], []),
    'updateUsername' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };