/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ThreadMessageSummary {
    participants: Array<Principal>;
    subject: string;
    messages: Array<Message>;
    totalMessages: bigint;
    unreadCount: bigint;
    latestMessage: Message;
    threadId: bigint;
}
export type Time = bigint;
export type MessageId = bigint;
export interface Attachment {
    hash: string;
    size: bigint;
    mimeType: string;
    filename: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface MessageUpdate {
    subject?: string;
    body?: string;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Payment {
    token: string;
    memo?: string;
    amount: bigint;
}
export interface Message {
    id: MessageId;
    deletedBySender: boolean;
    deletedByRecipient: boolean;
    subject: string;
    body: string;
    recipient: Principal;
    trashedByRecipient: boolean;
    isRead: boolean;
    sender: Principal;
    timestamp: Time;
    threadId: bigint;
    parentId?: MessageId;
    trashedBySender: boolean;
    attachments: Array<Attachment>;
    payment?: Payment;
}
export interface MessageInput {
    subject: string;
    body: string;
    recipient: Principal;
    parentId?: MessageId;
    attachments: Array<Attachment>;
    payment?: Payment;
}
export interface UserProfile {
    principal: Principal;
    username: string;
    registrationTime: Time;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAllMessages(): Promise<void>;
    deleteMessage(id: MessageId): Promise<void>;
    deleteThread(threadId: bigint): Promise<void>;
    emptyTrash(): Promise<void>;
    getAllMessages(): Promise<Array<Message>>;
    getAllMessagesByRecipient(): Promise<Array<Message>>;
    getAllMessagesBySender(): Promise<Array<Message>>;
    getAllMessagesBySenderAndRecipient(): Promise<Array<Message>>;
    getAllMessagesBySubject(): Promise<Array<Message>>;
    getAllMessagesByThread(): Promise<Array<Message>>;
    getAllMessagesByTimestamp(): Promise<Array<Message>>;
    getAllThreads(): Promise<Array<ThreadMessageSummary>>;
    getAllThreadsBySubject(): Promise<Array<ThreadMessageSummary>>;
    getAllThreadsByTimestamp(): Promise<Array<ThreadMessageSummary>>;
    getAllUsers(): Promise<Array<[Principal, string]>>;
    getAllUsersByPrincipal(): Promise<Array<[Principal, string]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversation(partner: Principal): Promise<Array<Message>>;
    getInbox(): Promise<Array<Message>>;
    getInboxBySender(): Promise<Array<Message>>;
    getInboxBySubject(): Promise<Array<Message>>;
    getInboxByThread(): Promise<Array<Message>>;
    getMessageById(id: MessageId): Promise<Message | null>;
    getOutbox(): Promise<Array<Message>>;
    getOutboxByRecipient(): Promise<Array<Message>>;
    getOutboxBySubject(): Promise<Array<Message>>;
    getOutboxByThread(): Promise<Array<Message>>;
    getOwnUsername(): Promise<string>;
    getPrincipalByUsername(username: string): Promise<Principal>;
    getThread(threadId: bigint): Promise<Array<Message>>;
    getTrash(): Promise<Array<Message>>;
    getUnreadMessageCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUsernameByPrincipal(principal: Principal): Promise<string>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isUsernameAvailable(username: string): Promise<boolean>;
    markAllMessagesAsRead(): Promise<void>;
    markMessageAsRead(id: MessageId): Promise<void>;
    register(username: string): Promise<void>;
    replyToMessage(messageId: MessageId, subject: string, body: string): Promise<MessageId>;
    restoreThread(threadId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedReplyChain(count: bigint | null): Promise<void>;
    seedSampleMessages(recipient: Principal | null, count: bigint | null): Promise<void>;
    sendMessage(input: MessageInput): Promise<MessageId>;
    sendMessageWithReply(message: Message): Promise<void>;
    trashThread(threadId: bigint): Promise<void>;
    updateMessage(id: MessageId, updates: MessageUpdate): Promise<void>;
    updateUsername(newUsername: string): Promise<void>;
}
import type { Attachment as _Attachment, Message as _Message, MessageId as _MessageId, MessageInput as _MessageInput, MessageUpdate as _MessageUpdate, Payment as _Payment, ThreadMessageSummary as _ThreadMessageSummary, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAllMessages(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllMessages();
            return result;
        }
    }
    async deleteMessage(arg0: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0);
            return result;
        }
    }
    async deleteThread(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteThread(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteThread(arg0);
            return result;
        }
    }
    async emptyTrash(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.emptyTrash();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.emptyTrash();
            return result;
        }
    }
    async getAllMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessages();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessages();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMessagesByRecipient(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessagesByRecipient();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessagesByRecipient();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMessagesBySender(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessagesBySender();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessagesBySender();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMessagesBySenderAndRecipient(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessagesBySenderAndRecipient();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessagesBySenderAndRecipient();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMessagesBySubject(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessagesBySubject();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessagesBySubject();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMessagesByThread(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessagesByThread();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessagesByThread();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMessagesByTimestamp(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessagesByTimestamp();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessagesByTimestamp();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllThreads(): Promise<Array<ThreadMessageSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllThreads();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllThreads();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllThreadsBySubject(): Promise<Array<ThreadMessageSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllThreadsBySubject();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllThreadsBySubject();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllThreadsByTimestamp(): Promise<Array<ThreadMessageSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllThreadsByTimestamp();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllThreadsByTimestamp();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<[Principal, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getAllUsersByPrincipal(): Promise<Array<[Principal, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersByPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersByPrincipal();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInbox(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInbox();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInbox();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInboxBySender(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInboxBySender();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInboxBySender();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInboxBySubject(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInboxBySubject();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInboxBySubject();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInboxByThread(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInboxByThread();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInboxByThread();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessageById(arg0: MessageId): Promise<Message | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageById(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageById(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOutbox(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOutbox();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOutbox();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOutboxByRecipient(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOutboxByRecipient();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOutboxByRecipient();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOutboxBySubject(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOutboxBySubject();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOutboxBySubject();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOutboxByThread(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOutboxByThread();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOutboxByThread();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnUsername(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnUsername();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnUsername();
            return result;
        }
    }
    async getPrincipalByUsername(arg0: string): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrincipalByUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrincipalByUsername(arg0);
            return result;
        }
    }
    async getThread(arg0: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getThread(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThread(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrash(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrash();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrash();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadMessageCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadMessageCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadMessageCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsernameByPrincipal(arg0: Principal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsernameByPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsernameByPrincipal(arg0);
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isUsernameAvailable(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUsernameAvailable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUsernameAvailable(arg0);
            return result;
        }
    }
    async markAllMessagesAsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllMessagesAsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllMessagesAsRead();
            return result;
        }
    }
    async markMessageAsRead(arg0: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageAsRead(arg0);
            return result;
        }
    }
    async register(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0);
            return result;
        }
    }
    async replyToMessage(arg0: MessageId, arg1: string, arg2: string): Promise<MessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.replyToMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replyToMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async restoreThread(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreThread(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreThread(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedReplyChain(arg0: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedReplyChain(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedReplyChain(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async seedSampleMessages(arg0: Principal | null, arg1: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleMessages(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleMessages(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async sendMessage(arg0: MessageInput): Promise<MessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(to_candid_MessageInput_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(to_candid_MessageInput_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessageWithReply(arg0: Message): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessageWithReply(to_candid_Message_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessageWithReply(to_candid_Message_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async trashThread(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trashThread(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trashThread(arg0);
            return result;
        }
    }
    async updateMessage(arg0: MessageId, arg1: MessageUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMessage(arg0, to_candid_MessageUpdate_n33(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMessage(arg0, to_candid_MessageUpdate_n33(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUsername(arg0);
            return result;
        }
    }
}
function from_candid_Message_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ThreadMessageSummary_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThreadMessageSummary): ThreadMessageSummary {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MessageId]): MessageId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payment]): Payment | null {
    return value.length === 0 ? null : from_candid_Payment_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Message]): Message | null {
    return value.length === 0 ? null : from_candid_Message_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    deletedBySender: boolean;
    deletedByRecipient: boolean;
    subject: string;
    body: string;
    recipient: Principal;
    trashedByRecipient: boolean;
    isRead: boolean;
    sender: Principal;
    timestamp: _Time;
    threadId: bigint;
    parentId: [] | [_MessageId];
    trashedBySender: boolean;
    attachments: Array<_Attachment>;
    payment: [] | [_Payment];
}): {
    id: MessageId;
    deletedBySender: boolean;
    deletedByRecipient: boolean;
    subject: string;
    body: string;
    recipient: Principal;
    trashedByRecipient: boolean;
    isRead: boolean;
    sender: Principal;
    timestamp: Time;
    threadId: bigint;
    parentId?: MessageId;
    trashedBySender: boolean;
    attachments: Array<Attachment>;
    payment?: Payment;
} {
    return {
        id: value.id,
        deletedBySender: value.deletedBySender,
        deletedByRecipient: value.deletedByRecipient,
        subject: value.subject,
        body: value.body,
        recipient: value.recipient,
        trashedByRecipient: value.trashedByRecipient,
        isRead: value.isRead,
        sender: value.sender,
        timestamp: value.timestamp,
        threadId: value.threadId,
        parentId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.parentId)),
        trashedBySender: value.trashedBySender,
        attachments: value.attachments,
        payment: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.payment))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: string;
    memo: [] | [string];
    amount: bigint;
}): {
    token: string;
    memo?: string;
    amount: bigint;
} {
    return {
        token: value.token,
        memo: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.memo)),
        amount: value.amount
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    participants: Array<Principal>;
    subject: string;
    messages: Array<_Message>;
    totalMessages: bigint;
    unreadCount: bigint;
    latestMessage: _Message;
    threadId: bigint;
}): {
    participants: Array<Principal>;
    subject: string;
    messages: Array<Message>;
    totalMessages: bigint;
    unreadCount: bigint;
    latestMessage: Message;
    threadId: bigint;
} {
    return {
        participants: value.participants,
        subject: value.subject,
        messages: from_candid_vec_n10(_uploadFile, _downloadFile, value.messages),
        totalMessages: value.totalMessages,
        unreadCount: value.unreadCount,
        latestMessage: from_candid_Message_n11(_uploadFile, _downloadFile, value.latestMessage),
        threadId: value.threadId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ThreadMessageSummary>): Array<ThreadMessageSummary> {
    return value.map((x)=>from_candid_ThreadMessageSummary_n19(_uploadFile, _downloadFile, x));
}
function to_candid_MessageInput_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageInput): _MessageInput {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_MessageUpdate_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageUpdate): _MessageUpdate {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_Message_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Message): _Message {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_Payment_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Payment): _Payment {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject: string;
    body: string;
    recipient: Principal;
    parentId?: MessageId;
    attachments: Array<Attachment>;
    payment?: Payment;
}): {
    subject: string;
    body: string;
    recipient: Principal;
    parentId: [] | [_MessageId];
    attachments: Array<_Attachment>;
    payment: [] | [_Payment];
} {
    return {
        subject: value.subject,
        body: value.body,
        recipient: value.recipient,
        parentId: value.parentId ? candid_some(value.parentId) : candid_none(),
        attachments: value.attachments,
        payment: value.payment ? candid_some(to_candid_Payment_n29(_uploadFile, _downloadFile, value.payment)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: string;
    memo?: string;
    amount: bigint;
}): {
    token: string;
    memo: [] | [string];
    amount: bigint;
} {
    return {
        token: value.token,
        memo: value.memo ? candid_some(value.memo) : candid_none(),
        amount: value.amount
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: MessageId;
    deletedBySender: boolean;
    deletedByRecipient: boolean;
    subject: string;
    body: string;
    recipient: Principal;
    trashedByRecipient: boolean;
    isRead: boolean;
    sender: Principal;
    timestamp: Time;
    threadId: bigint;
    parentId?: MessageId;
    trashedBySender: boolean;
    attachments: Array<Attachment>;
    payment?: Payment;
}): {
    id: _MessageId;
    deletedBySender: boolean;
    deletedByRecipient: boolean;
    subject: string;
    body: string;
    recipient: Principal;
    trashedByRecipient: boolean;
    isRead: boolean;
    sender: Principal;
    timestamp: _Time;
    threadId: bigint;
    parentId: [] | [_MessageId];
    trashedBySender: boolean;
    attachments: Array<_Attachment>;
    payment: [] | [_Payment];
} {
    return {
        id: value.id,
        deletedBySender: value.deletedBySender,
        deletedByRecipient: value.deletedByRecipient,
        subject: value.subject,
        body: value.body,
        recipient: value.recipient,
        trashedByRecipient: value.trashedByRecipient,
        isRead: value.isRead,
        sender: value.sender,
        timestamp: value.timestamp,
        threadId: value.threadId,
        parentId: value.parentId ? candid_some(value.parentId) : candid_none(),
        trashedBySender: value.trashedBySender,
        attachments: value.attachments,
        payment: value.payment ? candid_some(to_candid_Payment_n29(_uploadFile, _downloadFile, value.payment)) : candid_none()
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject?: string;
    body?: string;
}): {
    subject: [] | [string];
    body: [] | [string];
} {
    return {
        subject: value.subject ? candid_some(value.subject) : candid_none(),
        body: value.body ? candid_some(value.body) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
